//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FullScreenViewController.h"

#import "FavForwardLogicDelegate.h"
#import "SightViewDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WCNetworkMediaPlayerDelegate.h"

@class FavForwardLogicController, NSString, SightView, SimpleSightInfo, UIButton, UILabel;

@interface FavSightFullScreenViewController : FullScreenViewController <FavForwardLogicDelegate, WCActionSheetDelegate, SightViewDelegate, WCNetworkMediaPlayerDelegate>
{
    FavForwardLogicController *m_favForwardController;
    SimpleSightInfo *m_sightInfo;
    SightView *_sightView;
    UIButton *m_playAttachVideoButton;
    UILabel *_tipsLabel;
    int _fullPlayTimes;
    NSString *m_jumpDetailUrl;
    _Bool _hidden;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dealloc;
- (void)exitFullScreen:(id)arg1;
- (void)forwardSight:(id)arg1;
- (id)getFavForawrdViewController;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
- (id)initWithSightInfo:(id)arg1;
- (void)internalInitWithSightInfo:(id)arg1;
- (_Bool)isAd;
- (void)longPressFullScreenWindow:(id)arg1;
@property(retain, nonatomic) NSString *m_jumpDetailUrl; // @synthesize m_jumpDetailUrl;
- (void)onClickDetailButton;
- (void)onClickPlayAttachVideoBtn;
- (void)onClosePlayer;
- (void)onClosePlayerForViewDetail:(id)arg1;
- (void)onResumeSightView:(id)arg1;
- (void)playSight;
- (void)saveSight:(id)arg1;
- (void)setPlayAttachVideoButtonFrame;
- (_Bool)shouldAutorotate;
- (struct CGSize)sightVideoSize;
- (_Bool)sightView:(id)arg1 playbackDidReadEnd:(_Bool)arg2;
- (_Bool)stopAtLastVideoFrameWhenPlayEnd;
- (void)updateThumbImageIfNeededWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

