//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@protocol MMRichTextCoverViewDelegate <NSObject>
- (struct _NSRange)characterRangeAtIndex:(long long)arg1;
- (float)getLineHeight;
- (NSMutableArray *)getSelectRectsWithRange:(struct _NSRange)arg1;
- (NSString *)getStringWithRange:(struct _NSRange)arg1;
- (NSString *)getTextString;
- (float)getTextViewHeight;
- (long long)getTouchIndexWithTouchPoint:(struct CGPoint)arg1;
- (_Bool)isEmojiLocation:(unsigned long long)arg1 bStart:(_Bool)arg2;
@end

