//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "IAppViewControllerManagerExt.h"
#import "IMMFacebookMgrExt.h"
#import "IMsgExt.h"
#import "MMKernelExt.h"
#import "MessageObserverDelegate.h"
#import "PBMessageObserverDelegate.h"
#import "PasswordLogicDelegate.h"
#import "UIAlertViewDelegate.h"
#import "WCAccountBindPhoneControlLogicDelegate.h"
#import "WCAccountSetPasswordViewControllerDelegate.h"
#import "WCPrivacyPolicyControlLogicDelegate.h"
#import "initLogicControllerDelegate.h"
#import "whatsnewViewDelegateEx.h"

@class InitLogicController, LaunchImage, MMLoadingView, MMUIWindow, NSMutableArray, NSString, NSURL, PasswordLogic, ShowRatingAchive, UIAlertController, WCAccountBindPhoneControlLogic, WCOutWhatsNewViewController, WCPrivacyPolicyControlLogic, WCUIAlertView;

@interface PreEnterWechatLogic : MMObject <IMMFacebookMgrExt, IAppViewControllerManagerExt, WCPrivacyPolicyControlLogicDelegate, PBMessageObserverDelegate, MessageObserverDelegate, whatsnewViewDelegateEx, initLogicControllerDelegate, UIAlertViewDelegate, MMKernelExt, WCAccountBindPhoneControlLogicDelegate, IMsgExt, WCAccountSetPasswordViewControllerDelegate, PasswordLogicDelegate>
{
    vector_a9c0768e m_vecMesssageIdToListen;
    NSURL *m_nsFeedBackUrl;
    InitLogicController *m_initLogicController;
    MMLoadingView *m_loadingView;
    _Bool m_bCalledPreEnterWechatDone;
    _Bool m_bRunning;
    ShowRatingAchive *m_oShowingRating;
    WCAccountBindPhoneControlLogic *m_bindPhoneLogic;
    WCAccountBindPhoneControlLogic *m_changePhoneLogic;
    WCOutWhatsNewViewController *m_WhatsnewViewController;
    MMUIWindow *m_window;
    NSMutableArray *m_nsArrSteps;
    PasswordLogic *m_setPasswdLogic;
    PasswordLogic *m_changePasswdLogic;
    UIAlertController *m_globalAlertController;
    WCUIAlertView *m_globalAlert;
    LaunchImage *m_launchImage;
    WCPrivacyPolicyControlLogic *m_privacyPolicyLogic;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)MessageReturn:(unsigned int)arg1 MessageInfo:(id)arg2 Event:(unsigned int)arg3;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)callPreEnterWechatDone;
- (void)cancelAlert:(id)arg1 clickedButtonAtIndex:(id)arg2;
- (void)checkBindPhone:(id)arg1;
- (_Bool)checkDBAutoRecover;
- (void)checkHaveNotSetPassword:(id)arg1;
- (void)checkHaveSetPassword:(id)arg1;
- (void)checkShowRating;
- (void)checkStartSteps;
- (void)checkUpdateNewVersionTip:(_Bool)arg1;
- (void)checkUpdateTabbarBadgeNum;
- (void)cleanSetting;
- (void)closeFirstView;
- (void)dealloc;
- (void)delayLoadAndCheck;
- (void)delaySetPrivacyPolicyLogicNil;
- (void)enterForeground;
- (void)fixContactPlugin;
- (void)globalAlertReport:(id)arg1 Btn:(id)arg2;
- (void)goNext;
- (void)handleInitAndPhoneSync;
- (void)handleInitOk;
- (id)initFromReg:(_Bool)arg1;
- (void)initMessageIdToListen;
- (void)initSeviceObject;
- (void)messageReturnPrivacyPolicy:(id)arg1;
- (void)onFirstAskForRatingNo;
- (void)onFirstAskForRatingYes;
- (void)onFirstAskNo;
- (void)onFirstAskYes;
- (void)onForFeedbackNo;
- (void)onForFeedbackYes;
- (void)onGetUpdateInfoOk;
- (void)onRatingReport:(unsigned int)arg1;
- (void)onSetPasswordBack;
- (void)onSetPasswordOK;
- (void)onShowRatingDone;
- (void)onTabBarRootViewControllerDidAppear;
- (void)onTimeChange;
- (void)onWCAccountBindPhoneControlLogicCheckOK:(id)arg1;
- (void)onWCAccountBindPhoneControlLogicStop:(id)arg1;
- (void)onWCPrivacyPolicyControlLogicClickCancel;
- (void)onWCPrivacyPolicyControlLogicClickClose;
- (void)onWCPrivacyPolicyControlLogicClickDone;
- (void)openFeedBackWapPage:(id)arg1;
- (void)openFirstView;
- (void)parseGlobalAlert:(id)arg1;
- (void)parseShowPrivacyPolicy:(id)arg1;
- (void)parseShowTrustedFriends:(id)arg1;
- (void)passwordLogicCancel:(id)arg1;
- (void)passwordLogicPause:(id)arg1;
- (void)passwordLogicStart:(id)arg1;
- (void)percentIniting:(id)arg1;
- (void)preLoadContacts;
- (void)restoreContactDraft;
- (void)sendPrivacyPolicyChoice:(_Bool)arg1;
- (void)showBindPhoneInfoView:(id)arg1;
- (void)showCHSWhatsNew;
- (void)showChangePhone;
- (void)showChangePhone:(id)arg1 clickedButtonAtIndex:(id)arg2;
- (void)showGlobalAlert;
- (void)showScan;
- (void)showScan:(id)arg1 clickedButtonAtIndex:(id)arg2;
- (void)showSetPasswordView:(id)arg1;
- (void)showSyncAddrAlert;
- (void)showTrustedFriendsVC:(id)arg1;
- (void)showWebView:(id)arg1;
- (void)showWebView:(id)arg1 clickedButtonAtIndex:(id)arg2;
- (void)showWhatsNewEnd;
- (void)showWhatsNewWillEnd;
- (void)startChangePassward;
- (void)startChangePassward:(id)arg1 clickedButtonAtIndex:(id)arg2;
- (void)startLoading;
- (void)startSteps:(id)arg1;
- (void)stopIniting:(unsigned int)arg1;
- (void)stopLoading;
- (void)tryShowPswdView:(id)arg1;
- (void)tryShowWhatsNew;
- (void)unknownFail:(id)arg1;
- (void)verifyPasswordFail:(id)arg1;
- (void)verifyPasswordOK:(id)arg1 logic:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

