//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVPlayer, AVPlayerItem, NSString;

@protocol VideoStreamPlayerViewModeDelegate <NSObject>
- (void)OnSnsVideoChanged;
- (void)OnVideoDownloadErrorExpired:(_Bool)arg1;
- (void)ShouldUpdateThumbImage:(NSString *)arg1;
- (void)checkPlayerState;
- (AVPlayer *)getAVPlayer;
- (AVPlayerItem *)getAVPlayerItem;
- (double)getVideoBufferedTime;
- (double)getVideoCurrentSeconde;
- (void)onDownloadSuccess;
- (void)onVideoDownloadModeChange:(unsigned long long)arg1;
- (void)setBufferState:(_Bool)arg1;
- (void)tryToBeginPlayVideo;
- (void)tryToPauseAndStartLoading;
@end

