//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WAJSEventHandlerContextDelegate.h"

@class NSArray, NSCondition, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, NSThread, WAAppTaskExtInfo, WAJSContext, WAJSContextPluginScheduler, WAJSCoreServiceOpenData, WAWebViewController, WxaExternalInfo;

@interface WAJSCoreService : NSObject <WAJSEventHandlerContextDelegate>
{
    unsigned int _debugModeType;
    _Bool _isDebugAndVConsoleOpen;
    WxaExternalInfo *_wxaExternalInfo;
    unsigned long long _appVersion;
    unsigned int _appServiceMaxDataSize;
    WAAppTaskExtInfo *_taskExtInfo;
    NSString *_enterPath;
    unsigned int _enterScene;
    NSArray *_templates;
    unsigned int _nativeBufferSizeLimit;
    unsigned int _nativeBufferQueueLimit;
    unsigned long long _taskRunningState;
    _Bool _jsThreadSuspended;
    _Bool _jsThreadDying;
    NSCondition *_condition;
    NSString *lastError;
    _Bool _threadInjected;
    _Bool _hasInjectErr;
    _Bool _useCompatibleModeConvertData;
    id <WAJSCoreServiceDelegate> _delegate;
    WAWebViewController *_currentWebView;
    NSString *_serviceJSUrl;
    WAJSContextPluginScheduler *_pluginScheduler;
    unsigned long long _runningState;
    WAJSCoreServiceOpenData *_launchData;
    NSThread *_thread;
    WAJSContext *_context;
    NSString *_appID;
    NSMutableDictionary *_timerObjs;
    NSMutableSet *_eventHandlers;
    NSMutableArray *_prevEvents;
    NSMutableDictionary *_extraInfo;
}

- (void).cxx_destruct;
- (id)GetWeAppPluginByName:(id)arg1;
- (id)GetWebViewPluginByName:(id)arg1;
- (id)addNativeBuffer:(id)arg1;
- (unsigned int)addTimer:(unsigned int)arg1 withTime:(float)arg2 isRepeat:(_Bool)arg3;
@property(copy) NSString *appID; // @synthesize appID=_appID;
- (void)asyncPrintConsoleLogToCurrentWebView:(id)arg1;
- (void)asyncRunOperationBlockOnWorkThread:(CDUnknownBlockType)arg1;
- (_Bool)checkJSAPIRunInMainThread:(id)arg1;
- (_Bool)checkJSAPIRunMode:(id)arg1;
- (void)checkUserAuthWithJSAPI:(id)arg1 handler:(CDUnknownBlockType)arg2 failHandler:(CDUnknownBlockType)arg3;
- (void)checkWorkingThreadStatusWhenRunningStateChanged;
@property(retain) WAJSContext *context; // @synthesize context=_context;
@property(nonatomic) __weak WAWebViewController *currentWebView; // @synthesize currentWebView=_currentWebView;
- (void)dealloc;
@property(nonatomic) __weak id <WAJSCoreServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)endWithResult:(id)arg1 handler:(id)arg2;
- (void)endWithResult:(id)arg1 handler:(id)arg2 callbackID:(unsigned int)arg3;
@property(retain) NSMutableSet *eventHandlers; // @synthesize eventHandlers=_eventHandlers;
- (void)executeDelayToForegroundJSAPI;
@property(retain) NSMutableDictionary *extraInfo; // @synthesize extraInfo=_extraInfo;
- (id)getAppId;
- (id)getAppLaunchConfig;
- (unsigned long long)getAppVersion;
- (id)getCurrentWebView;
- (unsigned int)getDebugModeType;
- (id)getEventHandler:(id)arg1;
- (id)getPermissionWithJSAPI:(id)arg1;
- (id)getWxaExternalInfo;
@property _Bool hasInjectErr; // @synthesize hasInjectErr=_hasInjectErr;
- (id)init;
- (void)initJSContext:(id)arg1;
- (void)injectJSBaseForAppBrandThread:(id)arg1 wrapScript:(id)arg2;
- (void)injectJavaScript;
- (void)injectWeiXinNativeBuffer;
- (_Bool)isDebugAndVConsoleOpen;
- (_Bool)isJSInjected;
- (_Bool)isPlayingAudio;
@property(retain, nonatomic) WAJSCoreServiceOpenData *launchData; // @synthesize launchData=_launchData;
- (void)loadAppConfig;
- (unsigned int)nativeBufferTotalSize;
- (void)notifyJSInjectedOnMainThread:(id)arg1;
- (void)onAppBeforPushNavigation:(id)arg1;
- (void)onRunningStateDidChanged:(unsigned long long)arg1;
- (void)onRunningStateWillChanged:(unsigned long long)arg1;
- (void)onTimer:(id)arg1;
- (void)onWeAppEnterBackground:(long long)arg1;
- (void)onWeAppEnterForeground:(id)arg1 isFromSystemAwake:(_Bool)arg2;
- (id)parseInvokeHandlerNativeBufferParam:(id)arg1 getError:(id *)arg2;
- (id)parseNative2SdkNativeBufferParam:(id)arg1 getError:(id *)arg2;
- (void)performEventOnThread:(id)arg1;
@property(retain, nonatomic) WAJSContextPluginScheduler *pluginScheduler; // @synthesize pluginScheduler=_pluginScheduler;
- (id)popNativeBuffer:(id)arg1;
@property(retain) NSMutableArray *prevEvents; // @synthesize prevEvents=_prevEvents;
- (void)printConsoleLog:(id)arg1;
- (void)releaseJSContext;
- (void)removeHandler:(id)arg1;
- (void)reportApiCallResult:(id)arg1;
- (void)reportJSError:(id)arg1;
- (void)resumeWorkingThreadToDie:(_Bool)arg1;
- (void)runThread:(id)arg1;
@property(nonatomic) unsigned long long runningState; // @synthesize runningState=_runningState;
- (void)sendAppBrandEvent:(long long)arg1 param:(id)arg2 webviewID:(unsigned long long)arg3;
- (void)sendErrorEvent:(id)arg1;
- (void)sendInnerAppBrandEvent:(long long)arg1 param:(id)arg2 webviewID:(unsigned long long)arg3;
- (void)sendJSEventToService:(id)arg1 param:(id)arg2 webViewId:(unsigned int)arg3;
- (void)sendWebviewEventToService:(id)arg1 webViewId:(unsigned int)arg2;
@property(copy, nonatomic) NSString *serviceJSUrl; // @synthesize serviceJSUrl=_serviceJSUrl;
- (void)setEnterPath:(id)arg1 withScene:(unsigned int)arg2 taskExtInfo:(id)arg3;
- (void)setIsDebugAndVConsoleOpen:(_Bool)arg1;
- (void)setRefererInfo:(id)arg1 toDicParam:(id)arg2;
@property(retain) NSThread *thread; // @synthesize thread=_thread;
@property _Bool threadInjected; // @synthesize threadInjected=_threadInjected;
@property(retain) NSMutableDictionary *timerObjs; // @synthesize timerObjs=_timerObjs;
@property _Bool useCompatibleModeConvertData; // @synthesize useCompatibleModeConvertData=_useCompatibleModeConvertData;
- (void)setWxaExternalInfo:(id)arg1;
- (void)startAppBrand:(id)arg1 extraInfo:(id)arg2;
- (void)startServiceThread;
- (void)stopAppBrand;
- (void)stopAppBrandAndThread;
- (void)stopPlayingAudio;
- (void)suspendWorkingThread;
- (void)threadDidReceiveSuspend;
- (void)triggerStrictBanMode:(id)arg1;
- (void)workThread_invokeCallbackHandler:(id)arg1;
- (void)workThread_runOperationBlock:(CDUnknownBlockType)arg1;
- (void)workthread_sendJSEventToService:(id)arg1;
- (id)wxAppInfoJSONWithTemplate:(id)arg1 contactAttribute:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

