//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WAAppTaskReferrerInfo;

@interface WALoadingViewOpenWeAppInfo : NSObject
{
    unsigned int _debugMode;
    NSString *_appID;
    WAAppTaskReferrerInfo *_backReferrerInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appID; // @synthesize appID=_appID;
@property(retain, nonatomic) WAAppTaskReferrerInfo *backReferrerInfo; // @synthesize backReferrerInfo=_backReferrerInfo;
@property(nonatomic) unsigned int debugMode; // @synthesize debugMode=_debugMode;

@end

