//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCDBConfig : NSObject
{
    _Bool degenarateSync;
}

+ (id)ABTestConfig;
+ (id)configWithPath:(id)arg1;
+ (void)initialize;
@property(nonatomic) _Bool degenarateSync; // @synthesize degenarateSync;
- (id)description;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (id)init;
- (_Bool)writeToFile:(id)arg1;

@end

