//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMUIViewController, WNParagraphInfo;

@protocol WNArticleControllerDelegate <NSObject>

@optional
- (void)deleteRowAtIndex:(long long)arg1;
- (MMUIViewController *)getViewController;
- (void)hideLoadingView;
- (void)insertNewRowAtIndex:(long long)arg1;
- (void)insertNewRowAtIndex:(long long)arg1 withCount:(long long)arg2;
- (void)onNoneTxtInfoNumExceed;
- (void)onSelectAllViewToShow;
- (void)onSelectParaTextForEditing:(struct _NSRange)arg1;
- (void)onStopRecordVoice:(WNParagraphInfo *)arg1;
- (void)onTxtInfoTextLengthExceed;
- (void)refreshTableViewCellOnIndex:(long long)arg1;
- (void)reloadAll;
- (void)reloadRowAtIndex:(long long)arg1;
- (void)scrollToIndex:(long long)arg1;
- (void)showLoadingView;
@end

