//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WNParaObjectBaseView.h"

@class UIView;

@interface WNParaObjectFileView : WNParaObjectBaseView
{
    UIView *borderView;
}

- (void).cxx_destruct;
- (id)layoutDetailView:(double)arg1;
- (void)layoutView;
- (void)onClickObject;
- (void)onTouchBegin;
- (void)onTouchEnd;
- (void)setSelected;
- (void)setUnSelected;

@end

