//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WNParaObjectBaseView.h"

#import "ViewLocationDelegate.h"

@class NSString, UIView;

@interface WNParaObjectLocationNewView : WNParaObjectBaseView <ViewLocationDelegate>
{
    UIView *locationDetailView;
    UIView *borderView;
}

- (void).cxx_destruct;
- (void)layoutDetailView:(double)arg1;
- (void)layoutView;
- (void)onClickObject;
- (void)onSendLocationToFriend:(id)arg1 ViewController:(id)arg2;
- (void)onTouchBegin;
- (void)onTouchEnd;
- (void)setSelected;
- (void)setUnSelected;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

